Global stats enable success message
Qwant/qwant-viprivacy pull request #31
Opened 2022-06-30 15:48 UTC by raed667

Show a success message when global stats are enabled.

2022-06-30 16:20 UTC, Grafikart requested changes

2022-06-30 16:20 UTC, Grafikart commented on Extension/src/pages/popup/components/GlobalStatsView/GlobalStatsView.jsx
> +                        : reactTranslator.getMessage('global_stats_empty')}
Peut être simplifié

```js
reactTranslator.getMessage(showStatsEnabledSuccess ? 'global_stats_enabled_success' : 'global_stats_empty')
````

2022-06-30 16:20 UTC, Grafikart commented on Extension/src/pages/popup/components/GlobalStatsView/GlobalStatsView.jsx
> +function EmptyView({ showStatsEnabledSuccess }) {
Peut être trouver un nom plus simple pour cette props `justEnabled` ?

2022-07-01 09:19 UTC, raed667 commented
@Grafikart if it is ok with you, can I merge this PR ?

2022-07-01 09:29 UTC, merged